apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-web-upgrade
  labels:
    app.kubernetes.io/name: hi-web-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hi-web-upgrade
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hi-web-upgrade
    spec:
      imagePullSecrets:
        - name: test
      containers:
        - name: hi-web-upgrade
          image: devregistry11.azurecr.io/hi-web-upgrade:{IMAGE_VERSION}
          imagePullPolicy: Always
          env:
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      tolerations:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: "Equal"
            value: "spot"
            effect: "NoSchedule"
      nodeSelector:
          env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: hi-web-upgrade
  labels:
    app.kubernetes.io/name: hi-web-upgrade
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hi-web-upgrade

